---
-
  name: "Campfire"
  desc: "Campfire adapter"
  vars:
    -
      name: "HUBOT_CAMPFIRE_TOKEN"
      desc: "Campfire API token"
    -
      name: "HUBOT_CAMPFIRE_ROOMS"
      desc: "Campfire room IDs, separated by a commas"
    -
      name: "HUBOT_CAMPFIRE_ACCOUNT"
      desc: "Campfire account subdomain"

-
  name: "Email"
  desc: "Email adapter"
  vars:
    -
      name: "HUBOT_EMAIL_USERNAME"
      desc: "Email account username"
    -
      name: "HUBOT_EMAIL_PASSWORD"
      desc: "Email account password"
    -
      name: "HUBOT_IMAP_HOST"
      desc: "IMAP server address"
    -
      name: "HUBOT_IMAP_PORT"
      desc: "IMAP server port"
    -
      name: "HUBOT_IMAP_SECURE"
      desc: "IMAP sever secure connection, leave blank if not required"
    -
      name: "HUBOT_MAILBOX"
      desc: "IMAP mailbox to check"

-
  name: "Flowdock"
  desc: "Flowdock adapter"
  vars:
    -
      name: "HUBOT_FLOWDOCK_LOGIN_EMAIL"
      desc: "Flowdock login email"
    -
      name: "HUBOT_FLOWDOCK_LOGIN_PASSWORD"
      desc: "Flowdock login password"

-
  name: "GroupMe"
  desc: "GroupMe adapter"
  vars:
    -
      name: "HUBOT_GROUPME_ROOM"
      desc: "GroupMe room ID"
    -
      name: "HUBOT_GROUPME_TOKEN"
      desc: "GroupMe API token"

-
  name: "HipChat"
  desc: "HipChat adapter"
  vars:
    -
      name: "HUBOT_HIPCHAT_TOKEN"
      desc: "HipChat API token"
    -
      name: "HUBOT_HIPCHAT_JID"
      desc: "HipChat JID"
    -
      name: "HUBOT_HIPCHAT_NAME"
      desc: "HipChat name for your robot, leave blank to use the Robot name"
    -
      name: "HUBOT_HIPCHAT_PASSWORD"
      desc: "HipChat password"
    -
      name: "HUBOT_HIPCHAT_ROOMS"
      desc: "HipChat rooms to join, separated by commas, eave blank to join all"

-
  name: "IRC"
  desc: "IRC adapter"
  vars:
    -
      name: "HUBOT_IRC_NICK"
      desc: "IRC nick for your robot, leave blank to use the Robot name"
    -
      name: "HUBOT_IRC_SERVER"
      desc: "IRC server address"
    -
      name: "HUBOT_IRC_PORT"
      desc: "IRC server port, leave blank to use the default (6667)"
    -
      name: "HUBOT_IRC_ROOMS"
      desc: "IRC rooms, separated by commas"
    -
      name: "HUBOT_IRC_PASSWORD"
      desc: "IRC server password, leave blank if not required"
    -
      name: "HUBOT_IRC_NICKSERV_PASSWORD"
      desc: "IRC nickserv password, leave blank if not required"

-
  name: "Talker"
  desc: "Talker adapter"
  vars:
    -
      name: "HUBOT_TALKER_TOKEN"
      desc: "Talker API token"
    -
      name: "HUBOT_TALKER_ROOMS"
      desc: "Talker rooms to join, separated to commas"

-
  name: "Twitter"
  desc: "Twitter adapter"
  vars:
    -
      name: "HUBOT_TWITTER_KEY"
      desc: "Twitter OAuth key"
    -
      name: "HUBOT_TWITTER_SECRET"
      desc: "Twitter OAuth secret"
    -
      name: "HUBOT_TWITTER_TOKEN"
      desc: "Twitter OAuth token"
    -
      name: "HUBOT_TWITTER_TOKEN_SECRET"
      desc: "Twitter OAuth token secret"

-
  name: "Twilio"
  desc: "Twilio adapter"
  vars:
    -
      name: "HUBOT_SMS_SID"
      desc: "Twilio SID"
    - 
      name: "HUBOT_SMS_TOKEN"
      desc: "Twilio API token"
    -
      name: "HUBOT_SMS_FROM"
      desc: "Twilio number to send the reply from"

-
  name: "XMPP"
  desc: "XMPP adapters"
  vars:
    -
      name: "HUBOT_XMPP_USERNAME"
      desc: "XMPP account username"
    -
      name: "HUBOT_XMPP_PASSWORD"
      desc: "XMPP account password"
    -
      name: "HUBOT_XMPP_ROOMS"
      desc: "XMPP rooms, separated by commas"

