---
heroku_user: "heroku.provision.email"

email_host: "smtp.gmail.com"
email_port: "587"
email_user: "user@gmail.com"
email_pass: "userpassword"
email_domain: "yourdomain.com

hubot_bin: "/path/to/hubot/binary"

redis_host: "redis.server.com"
redis_port: 9508
redis_pass: "password"
